# Workflow from https://github.com/mitchellh/vouch/tree/main/action/setup-vouch/
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: mitchellh/vouch/action/setup-vouch@v1

      - run: vouch check someuser
